#include "sigmsgs.h"

Sigmsgs signals[] = {
	{"",	""},
	{"sighup",	"hangup"},
	{"sigint",	"interrupt"},
	{"sigquit",	"quit"},
	{"sigill",	"illegal instruction"},
	{"sigtrap",	"trace trap"},
	{"sigabrt",	"abort"},
	{"sigbus",	"bus error"},
	{"sigfpe",	"floating point error"},
	{"sigkill",	"killed"},
	{"sigusr1",	"user defined signal 1"},
	{"sigsegv",	"segmentation violation"},
	{"sigusr2",	"user defined signal 2"},
	{"sigpipe",	"broken pipe"},
	{"sigalrm",	"alarm clock"},
	{"sigterm",	"terminated"},
	{"sigstkflt",	"stack fault"},
	{"sigchld",	"child stop or exit"},
	{"sigcont",	"continue"},
	{"sigstop",	"stopped by program"},
	{"sigtstp",	"stopped"},
	{"sigttin",	"background tty read"},
	{"sigttou",	"background tty write"},
	{"sigurg",	"urgent condition on i/o channel"},
	{"sigxcpu",	"exceeded cpu time limit"},
	{"sigxfsz",	"exceeded file size limit"},
	{"sigvtalrm",	"virtual timer alarm"},
	{"sigprof",	"profiling timer alarm"},
	{"sigwinch",	"window size change"},
	{"sigio",	"socket i/o possible"},
	{"sigpwr",	"power-fail restart"},
	{"sigsys",	"invalid argument to system call"},
	{"sig32",	"unknown signal 32"},
	{"sig33",	"unknown signal 33"},
	{"sigrt0",	"real-time signal 0"},
	{"sigrt1",	"real-time signal 1"},
	{"sigrt2",	"real-time signal 2"},
	{"sigrt3",	"real-time signal 3"},
	{"sigrt4",	"real-time signal 4"},
	{"sigrt5",	"real-time signal 5"},
	{"sigrt6",	"real-time signal 6"},
	{"sigrt7",	"real-time signal 7"},
	{"sigrt8",	"real-time signal 8"},
	{"sigrt9",	"real-time signal 9"},
	{"sigrt10",	"real-time signal 10"},
	{"sigrt11",	"real-time signal 11"},
	{"sigrt12",	"real-time signal 12"},
	{"sigrt13",	"real-time signal 13"},
	{"sigrt14",	"real-time signal 14"},
	{"sigrt15",	"real-time signal 15"},
	{"sigrt16",	"real-time signal 16"},
	{"sigrt17",	"real-time signal 17"},
	{"sigrt18",	"real-time signal 18"},
	{"sigrt19",	"real-time signal 19"},
	{"sigrt20",	"real-time signal 20"},
	{"sigrt21",	"real-time signal 21"},
	{"sigrt22",	"real-time signal 22"},
	{"sigrt23",	"real-time signal 23"},
	{"sigrt24",	"real-time signal 24"},
	{"sigrt25",	"real-time signal 25"},
	{"sigrt26",	"real-time signal 26"},
	{"sigrt27",	"real-time signal 27"},
	{"sigrt28",	"real-time signal 28"},
	{"sigrt29",	"real-time signal 29"},
	{"sigrt30",	"real-time signal 30"},
};
